/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:         ["Manrope", "sans-serif"],
        h1:           ["Manrope"],
        h2:           ["Manrope"],
        "body-lg":    ["Manrope"],
        "body-md":    ["Manrope"],
        "label-caps": ["Manrope"],
      },
      fontSize: {
        "display":    ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2":         ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg":    ["18px", { lineHeight: "1.6", letterSpacing: "0",       fontWeight: "500" }],
        "body-md":    ["16px", { lineHeight: "1.5", letterSpacing: "0",       fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      colors: {
        /* ── Surfaces ── */
        surface:                    "#fbf8ff",
        "surface-dim":              "#dad8e8",
        "surface-bright":           "#fbf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f4f2ff",
        "surface-container":        "#eeecfc",
        "surface-container-high":   "#e8e6f6",
        "surface-container-highest":"#e3e1f0",
        "surface-tint":             "#2d3eff",
        "surface-variant":          "#e3e1f0",
        "on-surface":               "#1a1b25",
        "on-surface-variant":       "#444557",
        "inverse-surface":          "#2f2f3b",
        "inverse-on-surface":       "#f1effe",
        background:                 "#fbf8ff",
        "on-background":            "#1a1b25",
        /* ── Outline ── */
        outline:                    "#757589",
        "outline-variant":          "#c5c5da",
        /* ── Primary ── */
        primary:                    "#0015cd",
        "primary-container":        "#1b2efd",
        "on-primary":               "#ffffff",
        "on-primary-container":     "#c4c7ff",
        "inverse-primary":          "#bdc2ff",
        "primary-fixed":            "#e0e0ff",
        "primary-fixed-dim":        "#bdc2ff",
        "on-primary-fixed":         "#000668",
        "on-primary-fixed-variant": "#0018e4",
        /* ── Secondary ── */
        secondary:                    "#505f76",
        "secondary-container":        "#d0e1fb",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#54647a",
        "secondary-fixed":            "#d3e4fe",
        "secondary-fixed-dim":        "#b7c8e1",
        "on-secondary-fixed":         "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        /* ── Tertiary ── */
        tertiary:                    "#7f1100",
        "tertiary-container":        "#aa1a00",
        "on-tertiary":               "#ffffff",
        "on-tertiary-container":     "#ffbbae",
        "tertiary-fixed":            "#ffdad3",
        "tertiary-fixed-dim":        "#ffb4a5",
        "on-tertiary-fixed":         "#3e0400",
        "on-tertiary-fixed-variant": "#8e1400",
        /* ── Error ── */
        error:                "#ba1a1a",
        "error-container":    "#ffdad6",
        "on-error":           "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        xs:                 "0.5rem",
        sm:                 "1rem",
        md:                 "1.5rem",
        lg:                 "2rem",
        xl:                 "3rem",
        "container-padding":"2.5rem",
        gutter:             "1.5rem",
      },
      borderRadius: {
        sm:      "0.25rem",
        DEFAULT: "0.5rem",
        md:      "0.75rem",
        lg:      "1rem",
        xl:      "1.5rem",
        full:    "9999px",
      },
      boxShadow: {
        card:       "0 8px 40px -10px rgba(27,46,253,0.04)",
        "card-hover":"0 12px 48px -8px rgba(27,46,253,0.08)",
      },
    },
  },
  plugins: [],
};
